/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrInteger;

public class Enum extends AxdrInteger {

    public Enum() {
        super(0, 255, 0);
    }

    public Enum(byte[] code) {
        super(0, 255, 0);
        this.code = code;
    }

    public Enum(long val) {
        super(0, 255, val);
    }

}
