/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import java.io.IOException;
import java.io.InputStream;

import org.openmuc.jasn1.ber.BerByteArrayOutputStream;
import org.openmuc.jdlms.internal.asn1.axdr.AxdrType;
import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrSequenceOf;

public class Get_Request_With_List implements AxdrType {

    public static class SubSeqOf_attribute_descriptor_list
            extends AxdrSequenceOf<Cosem_Attribute_Descriptor_With_Selection> {

        @Override
        protected Cosem_Attribute_Descriptor_With_Selection createListElement() {
            return new Cosem_Attribute_Descriptor_With_Selection();
        }

        protected SubSeqOf_attribute_descriptor_list(int length) {
            super(length);
        }

        public SubSeqOf_attribute_descriptor_list() {
        } // Call empty base constructor

    }

    public byte[] code = null;
    public Invoke_Id_And_Priority invoke_id_and_priority = null;

    public SubSeqOf_attribute_descriptor_list attribute_descriptor_list = null;

    public Get_Request_With_List() {
    }

    public Get_Request_With_List(byte[] code) {
        this.code = code;
    }

    public Get_Request_With_List(Invoke_Id_And_Priority invoke_id_and_priority,
            SubSeqOf_attribute_descriptor_list attribute_descriptor_list) {
        this.invoke_id_and_priority = invoke_id_and_priority;
        this.attribute_descriptor_list = attribute_descriptor_list;
    }

    @Override
    public int encode(BerByteArrayOutputStream axdrOStream) throws IOException {

        int codeLength;

        if (code != null) {
            codeLength = code.length;
            for (int i = code.length - 1; i >= 0; i--) {
                axdrOStream.write(code[i]);
            }
        }
        else {
            codeLength = 0;
            codeLength += attribute_descriptor_list.encode(axdrOStream);

            codeLength += invoke_id_and_priority.encode(axdrOStream);

        }

        return codeLength;

    }

    @Override
    public int decode(InputStream iStream) throws IOException {
        int codeLength = 0;

        invoke_id_and_priority = new Invoke_Id_And_Priority();
        codeLength += invoke_id_and_priority.decode(iStream);

        attribute_descriptor_list = new SubSeqOf_attribute_descriptor_list();
        codeLength += attribute_descriptor_list.decode(iStream);

        return codeLength;
    }

    public void encodeAndSave(int encodingSizeGuess) throws IOException {
        BerByteArrayOutputStream axdrOStream = new BerByteArrayOutputStream(encodingSizeGuess);
        encode(axdrOStream);
        code = axdrOStream.getArray();
    }

    @Override
    public String toString() {
        return "sequence: {" + "invoke_id_and_priority: " + invoke_id_and_priority + ", attribute_descriptor_list: "
                + attribute_descriptor_list + "}";
    }

}
