/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrBitString;

public class Invoke_Id_And_Priority extends AxdrBitString {

    public Invoke_Id_And_Priority() {
        super(8);
    }

    public Invoke_Id_And_Priority(byte[] bytes) {
        super(bytes);
    }

}
