/**
 * Copyright 2012-17 Fraunhofer ISE
 *
 * This file is part of jDLMS.
 * For more information visit http://www.openmuc.org
 *
 * jDLMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * jDLMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with jDLMS.  If not, see <http://www.gnu.org/licenses/>.
 */
/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import java.io.IOException;
import java.io.InputStream;

import org.openmuc.jasn1.ber.BerByteArrayOutputStream;
import org.openmuc.jdlms.internal.asn1.axdr.AxdrType;

public class Parameterized_Access implements AxdrType {

    public byte[] code = null;
    public Integer16 variable_name = null;

    public Unsigned8 selector = null;

    public Data parameter = null;

    public Parameterized_Access() {
    }

    public Parameterized_Access(byte[] code) {
        this.code = code;
    }

    public Parameterized_Access(Integer16 variable_name, Unsigned8 selector, Data parameter) {
        this.variable_name = variable_name;
        this.selector = selector;
        this.parameter = parameter;
    }

    @Override
    public int encode(BerByteArrayOutputStream axdrOStream) throws IOException {

        int codeLength;

        if (code != null) {
            codeLength = code.length;
            for (int i = code.length - 1; i >= 0; i--) {
                axdrOStream.write(code[i]);
            }
        }
        else {
            codeLength = 0;
            codeLength += parameter.encode(axdrOStream);

            codeLength += selector.encode(axdrOStream);

            codeLength += variable_name.encode(axdrOStream);

        }

        return codeLength;

    }

    @Override
    public int decode(InputStream iStream) throws IOException {
        int codeLength = 0;

        variable_name = new Integer16();
        codeLength += variable_name.decode(iStream);

        selector = new Unsigned8();
        codeLength += selector.decode(iStream);

        parameter = new Data();
        codeLength += parameter.decode(iStream);

        return codeLength;
    }

    public void encodeAndSave(int encodingSizeGuess) throws IOException {
        BerByteArrayOutputStream axdrOStream = new BerByteArrayOutputStream(encodingSizeGuess);
        encode(axdrOStream);
        code = axdrOStream.getArray();
    }

    @Override
    public String toString() {
        return "sequence: {" + "variable_name: " + variable_name + ", selector: " + selector + ", parameter: "
                + parameter + "}";
    }

}
