/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrSequenceOf;

public class ReadRequest extends AxdrSequenceOf<Variable_Access_Specification> {

    @Override
    protected Variable_Access_Specification createListElement() {
        return new Variable_Access_Specification();
    }

    protected ReadRequest(int length) {
        super(length);
    }

    public ReadRequest() {
    } // Call empty base constructor

}
