/**
 * This class file was automatically generated by the AXDR compiler that is part of jDLMS (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.cosem;

import org.openmuc.jdlms.internal.asn1.axdr.types.AxdrInteger;

public class Unsigned32 extends AxdrInteger {

    public Unsigned32() {
        super(0, 4294967295L, 0);
    }

    public Unsigned32(byte[] code) {
        super(0, 4294967295L, 0);
        this.code = code;
    }

    public Unsigned32(long val) {
        super(0, 4294967295L, val);
    }

}
