/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import org.openmuc.jasn1.ber.types.BerOctetString;

public class AEQualifierForm2 extends BerOctetString {

    private static final long serialVersionUID = 1L;

    public AEQualifierForm2() {
    }

    public AEQualifierForm2(byte[] value) {
        super(value);
    }

}
