/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package org.openmuc.jdlms.internal.asn1.iso.acse;

import org.openmuc.jasn1.ber.types.BerObjectIdentifier;

public class MechanismName extends BerObjectIdentifier {

    private static final long serialVersionUID = 1L;

    public MechanismName() {
    }

    public MechanismName(byte[] code) {
        super(code);
    }

    public MechanismName(int[] value) {
        super(value);
    }

}
